// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/history.proto

package history

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *float64               `protobuf:"fixed64,1,opt,name=result,proto3,oneof" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResultRequest) Reset() {
	*x = SaveResultRequest{}
	mi := &file_proto_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResultRequest) ProtoMessage() {}

func (x *SaveResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResultRequest.ProtoReflect.Descriptor instead.
func (*SaveResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{0}
}

func (x *SaveResultRequest) GetResult() float64 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type SaveResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResultResponse) Reset() {
	*x = SaveResultResponse{}
	mi := &file_proto_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResultResponse) ProtoMessage() {}

func (x *SaveResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResultResponse.ProtoReflect.Descriptor instead.
func (*SaveResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{1}
}

func (x *SaveResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_history_proto protoreflect.FileDescriptor

const file_proto_history_proto_rawDesc = "" +
	"\n" +
	"\x13proto/history.proto\x12\ahistory\";\n" +
	"\x11SaveResultRequest\x12\x1b\n" +
	"\x06result\x18\x01 \x01(\x01H\x00R\x06result\x88\x01\x01B\t\n" +
	"\a_result\".\n" +
	"\x12SaveResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2W\n" +
	"\x0eHistoryService\x12E\n" +
	"\n" +
	"SaveResult\x12\x1a.history.SaveResultRequest\x1a\x1b.history.SaveResultResponseB\x19Z\b/history\xaa\x02\fHistory.Grpcb\x06proto3"

var (
	file_proto_history_proto_rawDescOnce sync.Once
	file_proto_history_proto_rawDescData []byte
)

func file_proto_history_proto_rawDescGZIP() []byte {
	file_proto_history_proto_rawDescOnce.Do(func() {
		file_proto_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_history_proto_rawDesc), len(file_proto_history_proto_rawDesc)))
	})
	return file_proto_history_proto_rawDescData
}

var file_proto_history_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_history_proto_goTypes = []any{
	(*SaveResultRequest)(nil),  // 0: history.SaveResultRequest
	(*SaveResultResponse)(nil), // 1: history.SaveResultResponse
}
var file_proto_history_proto_depIdxs = []int32{
	0, // 0: history.HistoryService.SaveResult:input_type -> history.SaveResultRequest
	1, // 1: history.HistoryService.SaveResult:output_type -> history.SaveResultResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_history_proto_init() }
func file_proto_history_proto_init() {
	if File_proto_history_proto != nil {
		return
	}
	file_proto_history_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_history_proto_rawDesc), len(file_proto_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_history_proto_goTypes,
		DependencyIndexes: file_proto_history_proto_depIdxs,
		MessageInfos:      file_proto_history_proto_msgTypes,
	}.Build()
	File_proto_history_proto = out.File
	file_proto_history_proto_goTypes = nil
	file_proto_history_proto_depIdxs = nil
}
